### ISSUE TITLE
license_plate = np.invert(DetectPlate.plate_like_objects[0]) IndexError: list index out of range

### ISSUE THREAD

**Issue by utkarsh9450** [apoorva-dave/LicensePlateDetector#17]
hi @apoorva-dave  your project works best for the already input videos and images but whenever i try to take video created by me as input the bounding boxes are not created and the following error comes ,could u please provide any solution for this issue.

**Comment by apoorva-dave** [comment]
This error comes when no plate is detected. You can try the following -
1. Instead of working on videos directly first see if you are able to detect license plate in an image ( a frame of the video that you are giving as input.) Debugging will become easier for image.
2. If you are facing issues in that, try updating the breadth and height of the license plate that I am assuming in the code. Try to see what is getting detected.
Also the code doesn't handle corner cases where image of car is not properly aligned.

**Comment by utkarsh9450** [comment]
Thank you for your response. I implemented the same and found it to be
working fine.
